### ISSUE TITLE
boradcastAddress is wrong in Calculate function

### ISSUE THREAD

**Issue by NikhilMJagtap** [FreddyJilson/netools#13]
Broadcast address being returned is wrong in Calculate function.
It should be the BITWISE OR of Network Address and Inverted Subnet Mask.
Assign this to me, I will send the pull request.
Another suggestion is to change number of hosts to int from float32.

**Comment by FreddyJilson** [comment]
Thanks @NikhilMJagtap, I have responded to you earlier here in Issue [4](https://github.com/FreddyJilson/netools/issues/4)
