### ISSUE TITLE
Create Port scanner

### ISSUE THREAD

**Issue by FreddyJilson** [FreddyJilson/netools#7]
Implement port scanner cli to scan and display open/close ports.

**Flags**
* --host: The hostname or address that you want to scan (ie: --host google.com, --host 127.0.0.1)
* --udp or -u: Change the scan protocol from TCP to UDP
* --port or -p: Set a single port (ie: -p 80, --port 8080)
* --port-range: Set a range of ports to scan (ie: --port-range 80-8080)
* --port-list: Sets a list of ports to scan (ie: --port-list 80,8080,5432,3000)

**Comment by caioeverest** [comment]
Hey, @FreddyJilson! Can I give it a try?

**Comment by FreddyJilson** [comment]
Hey @caioeverest! Sure of course! I have updated the description a bit for the port scanner to implement. If you feel there is any other additional features for port scanner you would like to add, please do so. Thanks.

**Comment by FreddyJilson** [comment]
Thank you @caioeverest! Have merged the pull request.
